//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;
//using Microsoft.EntityFrameworkCore;

//namespace ProductService.Models;

//public partial class ProductDBContext : DbContext
//{
//    public ProductDBContext(DbContextOptions<ProductDBContext> options)
//        : base(options)
//    {
//    }

//    public virtual DbSet<PetStoreUser> PetStoreUsers { get; set; }

//    protected override void OnModelCreating(ModelBuilder modelBuilder)
//    {
//        modelBuilder.Entity<PetStoreUser>(entity =>
//        {
//            entity.HasKey(e => e.ID).HasName("PetStoreUsers_pkey");

//            entity.Property(e => e.ID).ValueGeneratedNever();
//        });

//        OnModelCreatingPartial(modelBuilder);
//    }

//    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
//}